/**
 * 8 位演示新人：工号 E00001–E00008，密码统一 123456
 * 仅 E00001 为首次接入（未完成盲盒）；其余直接进入功能界面
 */
export const EIGHT_DEMO_NEWCOMERS = [
  {
    id: 'u-newcomer-001',
    username: 'E00001',
    dingtalk: 'dev_newcomer',
    nickname: '程序员小智',
    dept: '内容创作部门',
    persona: '静谧 I 人忍者型',
    tags: ['独处充电', '文档达人', '咖啡续命'],
    motto: '不打扰是我的温柔，交付是我的靠谱。',
    energy: 72,
    dominant: 'I' as const,
    firstTime: true,
  },
  {
    id: 'u-newcomer-002',
    username: 'E00002',
    dingtalk: 'dev_partner',
    nickname: '产品小美',
    dept: '账号运营部门',
    persona: '社交 E 人带玩型',
    tags: ['饭局发起人', '气氛组', '跨界聊得来'],
    motto: '先连接人，再连接事——团队节奏我来带。',
    energy: 58,
    dominant: 'E' as const,
    firstTime: false,
  },
  {
    id: 'u-newcomer-003',
    username: 'E00003',
    dingtalk: 'newcomer_nd',
    nickname: '数据小鹿',
    dept: '数据分析部门',
    persona: '观察 N 人策谋型',
    tags: ['错峰出行', '信息敏感', '低调进场'],
    motto: '先看清局面再开口，是我的职场安全感。',
    energy: 65,
    dominant: 'N' as const,
    firstTime: false,
  },
  {
    id: 'u-newcomer-004',
    username: 'E00004',
    dingtalk: 'newcomer_nb',
    nickname: '商务 Lily',
    dept: '商务市场部门',
    persona: '踏实 S 人守护型',
    tags: ['步骤清晰', '靠谱搭子', '桌游局常驻'],
    motto: '一步一步来，把小事做好就是最好的融入。',
    energy: 55,
    dominant: 'S' as const,
    firstTime: false,
  },
  {
    id: 'u-newcomer-005',
    username: 'E00005',
    dingtalk: 'newcomer_nf',
    nickname: '行政小周',
    dept: '职能部门',
    persona: '玩梗 P 人协作型',
    tags: ['表情包外交', '群聊活跃', '灵感快闪'],
    motto: '严肃问题也可以轻松问，求助不丢人。',
    energy: 80,
    dominant: 'P' as const,
    firstTime: false,
  },
  {
    id: 'u-newcomer-006',
    username: 'E00006',
    dingtalk: 'newcomer_nc2',
    nickname: '内容小新',
    dept: '内容创作部门',
    persona: '静谧 I 人忍者型',
    tags: ['文档达人', '独处充电'],
    motto: '不打扰是我的温柔，交付是我的靠谱。',
    energy: 68,
    dominant: 'I' as const,
    firstTime: false,
  },
  {
    id: 'u-newcomer-007',
    username: 'E00007',
    dingtalk: 'newcomer_no2',
    nickname: '运营阿凯',
    dept: '账号运营部门',
    persona: '社交 E 人带玩型',
    tags: ['饭局发起人', '气氛组'],
    motto: '先连接人，再连接事。',
    energy: 62,
    dominant: 'E' as const,
    firstTime: false,
  },
  {
    id: 'u-newcomer-008',
    username: 'E00008',
    dingtalk: 'newcomer_nd2',
    nickname: '策略晨晨',
    dept: '数据分析部门',
    persona: '观察 N 人策谋型',
    tags: ['信息敏感', '先谋后动'],
    motto: '先看清局面再开口，是我的职场安全感。',
    energy: 70,
    dominant: 'N' as const,
    firstTime: false,
  },
] as const;

export const FIRST_TIME_USERNAME = 'E00001';
