/**
 * 8 位演示新人（与 hepai-server/src/db/demoNewcomers.ts 对齐）
 */
export const EIGHT_DEMO_NEWCOMERS = [
  {
    username: 'E00001',
    userId: 'u-newcomer-001',
    nickname: '程序员小智',
    dept: '内容创作部门',
    personaName: '静谧 I 人忍者型',
    personaTags: ['独处充电', '文档达人', '咖啡续命'],
    personaMotto: '不打扰是我的温柔，交付是我的靠谱。',
    dominant: 'I',
    energy: 72,
    firstTime: true,
  },
  {
    username: 'E00002',
    userId: 'u-newcomer-002',
    nickname: '产品小美',
    dept: '账号运营部门',
    personaName: '社交 E 人带玩型',
    personaTags: ['饭局发起人', '气氛组', '跨界聊得来'],
    personaMotto: '先连接人，再连接事——团队节奏我来带。',
    dominant: 'E',
    energy: 58,
    firstTime: false,
  },
  {
    username: 'E00003',
    userId: 'u-newcomer-003',
    nickname: '数据小鹿',
    dept: '数据分析部门',
    personaName: '观察 N 人策谋型',
    personaTags: ['错峰出行', '信息敏感', '低调进场'],
    personaMotto: '先看清局面再开口，是我的职场安全感。',
    dominant: 'N',
    energy: 65,
    firstTime: false,
  },
  {
    username: 'E00004',
    userId: 'u-newcomer-004',
    nickname: '商务 Lily',
    dept: '商务市场部门',
    personaName: '踏实 S 人守护型',
    personaTags: ['步骤清晰', '靠谱搭子', '桌游局常驻'],
    personaMotto: '一步一步来，把小事做好就是最好的融入。',
    dominant: 'S',
    energy: 55,
    firstTime: false,
  },
  {
    username: 'E00005',
    userId: 'u-newcomer-005',
    nickname: '行政小周',
    dept: '职能部门',
    personaName: '玩梗 P 人协作型',
    personaTags: ['表情包外交', '群聊活跃', '灵感快闪'],
    personaMotto: '严肃问题也可以轻松问，求助不丢人。',
    dominant: 'P',
    energy: 80,
    firstTime: false,
  },
  {
    username: 'E00006',
    userId: 'u-newcomer-006',
    nickname: '内容小新',
    dept: '内容创作部门',
    personaName: '静谧 I 人忍者型',
    personaTags: ['文档达人', '独处充电'],
    personaMotto: '不打扰是我的温柔，交付是我的靠谱。',
    dominant: 'I',
    energy: 68,
    firstTime: false,
  },
  {
    username: 'E00007',
    userId: 'u-newcomer-007',
    nickname: '运营阿凯',
    dept: '账号运营部门',
    personaName: '社交 E 人带玩型',
    personaTags: ['饭局发起人', '气氛组'],
    personaMotto: '先连接人，再连接事。',
    dominant: 'E',
    energy: 62,
    firstTime: false,
  },
  {
    username: 'E00008',
    userId: 'u-newcomer-008',
    nickname: '策略晨晨',
    dept: '数据分析部门',
    personaName: '观察 N 人策谋型',
    personaTags: ['信息敏感', '先谋后动'],
    personaMotto: '先看清局面再开口，是我的职场安全感。',
    dominant: 'N',
    energy: 70,
    firstTime: false,
  },
] as const;

export const DEMO_NEWCOMER_PASSWORD = '123456';
